# Generated by Django 2.1.1 on 2018-11-11 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20181102_0950'),
        ('event', '0003_auto_20181102_0324'),
    ]

    operations = [
    ]
