# Generated by Django 2.1.2 on 2018-10-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category_name',
            field=models.CharField(default='enter menu category', max_length=100),
        ),
    ]
