# Generated by Django 2.1.2 on 2018-11-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='name', max_length=50)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=50, null=True)),
                ('total_persons', models.CharField(max_length=4)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
