# Generated by Django 2.1.1 on 2018-11-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='message',
            new_name='user_message',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='customer name', max_length=50),
        ),
    ]
